### PR TITLE
connection pool support

### PR DESCRIPTION
**Pull request by ovidiucp**
Hi Luke,

I've added support for connection pools. Please let me know how this looks to you.

Thanks,
Ovidiu

### CODE REVIEW

**Comment by kieransimkin** [comment]
Hi Ovidiu,
Thanks for the contribution, Luke's currently working on other stuff but we'll get your code reviewed and assuming it's all good included in the next release of txMySQL

Cheers,

~Kieran

**Comment by ovidiucp** [comment]
Hi Kieran,

No problem.

In the meantime check out some benchmarks I've done against txMySQL running
on top of twisted and Tornado:

https://github.com/ovidiucp/pymysql-benchmarks

Ovidiu

**Comment by lukemarsden** [comment]
Thanks for the connection pool support, ovidiucp! The benchmarks are interesting, but not that surprising. Firstly it's C versus Python, so a constant factor difference is expected, but mainly because no work has been done to even look at the performance characteristics of the state machine implementation used by txMySQL -- in our application, MySQL usage is very light, the reason that txMySQL got invented at all is that Python + FreeBSD + Twisted + threadpooling + very heavy network load causes incomprehensible segfaults inside libmysqlclient.

If you're interested in improving the performance characteristics I would recommend looking at running btt on the reactor while it's doing some intensive I/O:

http://twistedmatrix.com/pipermail/twisted-python/2011-June/024118.html

This will highlight the hotspots and I suspect it shouldn't be too tricky to get several factors improvement in the performance of txMySQL just by optimising a few internal data structures.

Thank you for your contribution! :-)

**Comment by ovidiucp** [comment]
Hi Luke,

Excellent, thanks! I'll spend some time looking for some hot spots.

Have fun,
Ovidiu

**Pull request merged**
